version: '0.1.0'
services:
    src:
        build: ./src/
        ports:
          - "8080:8080"
          - "443:443"
    tests:
        build: ./tests/
        depends_on:
          - src
        ports:
          - "8080:8080"
          - "443:443"
        volumes:
            - ./
        stdin_open: true
        tty: true
